// {
//     'title':'',  // 标题。加粗的部分可以使用<b></b>包裹，例如'we use <b>bold text</b> to emphsize our point.'
//     'year':'',  // 年份
//     'paperlink':'', // paper的网址
//     'arxivlink':'', // 对应arxiv开源版的网址。若为''则不显示arxiv按钮
//     'codelink':'', // 对应开源代码的网址。若为''则不显示code按钮
// },

publications = [
        {
        'title': 'Ying Hu, Chenyi Zhuang, Pan Gao. 2024. "DiffuseST: Unleashing the Capability of the Diffusion Model for Style Transfer," in ACM MM Asia',
        'year':2024,
        'paperlink':'',
        'arxivlink': '',
        'codelink':'',
      },
 {
        'title': 'Chenyi Zhuang, Ying Hu, Pan Gao. 2024. "Magnet: We Never Know How Text-to-Image Diffusion Models Work, Until We Learn How Vision-Language Models Function," in NeurIPS',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2409.19967',
        'codelink':'https://github.com/I2-Multimedia-Lab/Magnet',
      },
            {
        'title': 'jing Xu, Wentao Shi, Pan Gao, Qizhu Li,  Zhengwei Wang. 2024. "MUSTER: A Multi-Scale Transformer-Based Decoder for Semantic Segmentation," in IEEE Transactions on Emerging Topics in Computational Intelligence',
        'year':2024,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/10669920',
        'arxivlink': 'https://arxiv.org/abs/2211.13928',
        'codelink':'https://github.com/shiwt03/MUSTER',
      }, 
      {
        'title': 'Zihao Li, Pan Gao, Kang You, Chuan Yan, Manoranjan Paul. 2024. "Global Attention-Guided Dual-Domain Point Cloud Feature Learning for Classification and Segmentation," in IEEE Transactions on Artificial Intelligence',
        'year':2024,
        'paperlink':'',
        'arxivlink': '',
        'codelink':'',
      }, 
      {
        'title': 'Jinsong shi, Pan Gao, Xiaojiang Peng, Jie Qin. 2024. "DSMix: Distortion-Induced Sensitivity Map Based Pre-training for No-Reference Image Quality Assessment," in ECCV',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2407.03886',
        'codelink':'https://github.com/I2-Multimedia-Lab/DSMix',
      }, 
      {
        'title': 'Kang You, Kai Liu, Li Yu, Pan Gao, Dandan Ding. 2024. "Pointsoup: High-Performance and Extremely Low-Decoding-Latency Learned Geometry Codec for Large-Scale Point Cloud Scenes," in IJCAI',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2404.13550',
        'codelink':'https://github.com/I2-Multimedia-Lab/Pointsoup',
      },   
      {
        'title': 'Yao Yuan, Wutao Liu, Pan Gao, Qun Dai, Jie Qin. 2024. "Unified Unsupervised Salient Object Detection via Knowledge Transfer," in IJCAI',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2404.14759',
        'codelink':'https://github.com/I2-Multimedia-Lab/A2S-v3',
      },   
      {
        'title': 'Qingguo Liu, Chengyi Zhuang, Pan Gao, Jie Qin. 2024. "CDFormer: When Degradation Prediction Embraces Diffusion Model for Blind Image Super-Resolution," in CVPR',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2405.07648',
        'codelink':'https://github.com/I2-Multimedia-Lab/CDFormer',
       },   

  {
        'title': 'Sizhe Zheng, Pan Gao, Peng Zhou, Jie Qin. 2024. "Puff-Net: Efficient Style Transfer with Pure Content and Style Feature Fusion Network," in CVPR',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2405.19775',
        'codelink':'https://github.com/ZszYmy9/Puff-Net',
       },   
         {
        'title': 'Qingguo Liu, Pan Gao, Kang Han, Ningzhong Liu, Wei Xiang. 2024. "Degradation-Aware Self-Attention Based Transformer for Blind Image Super-Resolution," in IEEE Transactions on Multimedia',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/pdf/2310.04180.pdf',
        'codelink':'https://github.com/I2-Multimedia-Lab/DSAT',
       },       
  
  {
        'title': 'Jinsong Shi, Pan Gao, Jie Qin. 2024. "Transformer-based No-Reference Image Quality Assessment via Supervised Contrastive Learning," in AAAI 2024',
        'year':2024,
        'paperlink':'',
        'arxivlink': 'https://arxiv.org/abs/2312.06995',
        'codelink':'https://github.com/I2-Multimedia-Lab/SaTQA',
       },

  
                 {
        'title': 'ShanShan Li, Pan Gao, Xiaoyang Tan, Wei Xiang. 2023. "RLGrid: Reinforcement Learning Controlled Grid Deformation for Coarse-to-Fine Point Could Completion," in IEEE Transactions on Multimedia, DOI: 10.1109/TMM.2023.3318327',
        'year':2023,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/10261217',
        'arxivlink': '',
        'codelink':'https://github.com/I2-Multimedia-Lab/RLGrid',
       },

     {
        'title': 'Jinsong Shi, Pan Gao, Aljosa Smolic. 2023. "Blind Image Quality Assessment via Transformer Predicted Error Map and Perceptual Quality Token," in IEEE Transactions on Multimedia, DOI: 10.1109/TMM.2023.3325719',
        'year':2023,
        'paperlink':'https://ieeexplore.ieee.org/document/10287911',
        'arxivlink': 'https://arxiv.org/abs/2305.09353',
        'codelink':'https://github.com/I2-Multimedia-Lab/TempQT',
       },
            {
        'title': 'Chenyi Zhuang, Pan Gao, Aljosa Smolic. 2023. "StylePrompter: All Styles Need Is Attention," in ACM International Conference on Multimedia (MM), Ottawa, Canada.',
        'year':2023,
        'paperlink':'',
        'arxivlink':'https://arxiv.org/abs/2307.16151',
        'codelink':'https://github.com/I2-Multimedia-Lab/StylePrompter',
       },
         {
        'title': 'Pan Gao, Haoyue Tian, and Jie Qin. 2023. "Video Frame Interpolation with Flow Transformer," in ACM International Conference on Multimedia (MM), Ottawa, Canada.',
        'year':2023,
        'paperlink':'',
        'arxivlink':'https://arxiv.org/abs/2307.16144',
        'codelink':'',
    },
     {
        'title': 'Yihan Tang, Pan Gao, and Zhengwei Wang. 2023. "SalDA: DeepConvNet Greets Attention for Visual Saliency Prediction," in IEEE Transactions on Cognitive and Developmental Systems, pp. 1-15.',
        'year':2023,
        'paperlink':'https://ieeexplore.ieee.org/document/10122791',
        'arxivlink':'',
        'codelink':'https://github.com/Cony-Atalas/SalDA',
    },
     {
        'title': 'Shanshan Li, Pan Gao, Xiaoyang Tan and Mingqiang Wei. 2023. "ProxyFormer: Proxy Alignment Assisted Point Cloud Completion with Missing Part Sensitive Transformer," in IEEE/CVF Computer Vision and Pattern Recognition (CVPR).',
        'year':2023,
        'paperlink':'',
        'arxivlink':'https://arxiv.org/abs/2302.14435',
        'codelink':'https://github.com/I2-Multimedia-Lab/ProxyFormer',
    },
       {
        'title': 'Zihao Li, Pan Gao, Hui Yuan, Ran Wei and M. Paul. 2023. "Exploiting Inductive Bias in Transformer for Point Cloud Classification and Segmentation," in IEEE Conf. Multimedia and Expo (ICME) Workshops.',
        'year':2023,
        'paperlink':'',
        'arxivlink':'https://arxiv.org/abs/2304.14124',
        'codelink':'https://github.com/jiamang/IBT',
    },
        {
        'title': 'Pan Gao, S. Luo and Manoranjan Paul. 2023. "Rate-Distortion Modeling for Bit Rate Constrained Point Cloud Compression," in IEEE Transactions on Circuits and Systems for Video Technology, vol. 33. no. 5, pp. 2424-2438.',
        'year':2023,
        'paperlink':'https://ieeexplore.ieee.org/document/9957096',
        'arxivlink':'',
        'codelink':'',
    },
    {
        'title':"Kang You, Pan Gao, and Qing Li. 2022. IPDAE: Improved Patch-Based Deep Autoencoder for Lossy Point Cloud Geometry Compression. In Proceedings of the 1st International Workshop on Advances in Point Cloud Compression, Processing and Analysis (APCCPA '22). Association for Computing Machinery, New York, NY, USA, 1–10.",
        'year':2022,
        'paperlink':'https://dl.acm.org/doi/abs/10.1145/3552457.3555728',
        'arxivlink':'https://arxiv.org/abs/2208.02519',
        'codelink':'https://github.com/I2-Multimedia-Lab/IPDAE',
    },
    {
        'title':"Haoyue Tian, Pan Gao, Ran Wei, Manoranjan Paul: Dilated Convolutional Neural Network-Based Deep Reference Picture Generation for Video Compression. ICASSP 2022: 2824-2828",
        'year':2022,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/9747502/',
        'arxivlink':'https://arxiv.org/abs/2202.05514',
        'codelink':'https://github.com/I2-Multimedia-Lab/Dilated-CNN-based-deep-reference-picture-generation',
    },
    {
        'title':"Haoyue Tian, Pan Gao, Xiaojiang Peng: Video Frame Interpolation Based on Deformable Kernel Region. IJCAI 2022: 1349-1355.",
        'year':2022,
        'paperlink':'https://www.ijcai.org/proceedings/2022/0188.pdf',
        'arxivlink':'https://arxiv.org/abs/2204.11396',
        'codelink':'https://github.com/I2-Multimedia-Lab/Video-Frame-Interpolation-Based-on-Deformable-Kernel-Region',
    },
    {
        'title':"Kang You and Pan Gao. 2022. Patch-Based Deep Autoencoder for Point Cloud Geometry Compression. In ACM Multimedia Asia (MMAsia '21). Association for Computing Machinery, New York, NY, USA, Article 30, 1–7.",
        'year':2021,
        'paperlink':'https://dl.acm.org/doi/abs/10.1145/3469877.3490611',
        'arxivlink':'https://arxiv.org/abs/2110.09109',
        'codelink':'https://github.com/I2-Multimedia-Lab/PCC_Patch',
    },
    {
        'title':'X. Chen, P. Gao and R. Wei, "Visual Saliency Prediction on 360 Degree Images With CNN," 2021 IEEE International Conference on Multimedia & Expo Workshops (ICMEW), Shenzhen, China, 2021, pp. 1-6.',
        'year':2021,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/9456008',
        'arxivlink':'',
        'codelink':'',
    },
    {
        'title':'Pan Gao, Tiantian Zhu, Manoranjan Paul, Disocclusion filling for depth-based view synthesis with adaptive utilization of temporal correlations, Journal of Visual Communication and Image Representation, Volume 78, 2021, 103148, ISSN 1047-3203.',
        'year':2021,
        'paperlink':'https://www.sciencedirect.com/science/article/abs/pii/S1047320321000912',
        'arxivlink':'',
        'codelink':'',
    },
    {
        'title':'Cheng Zhang and Pan Gao, Defending Adversaries Using  Unsupervised Feature Clustering VAE, ICML 2021 Workshop on Adversarial Machine Learning, 2021.',
        'year':2021,
        'paperlink':'https://openreview.net/forum?id=C0slFCG5ayh',
        'arxivlink':'https://openreview.net/pdf?id=C0slFCG5ayh',
        'codelink':'',
    },
    {
        'title':'Cheng Zhang, Pan Gao; Countering Adversarial Examples: Combining Input Transformation and Noisy Training. Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV) Workshops, 2021, pp. 102-111.',
        'year':2021,
        'paperlink':'https://openaccess.thecvf.com/content/ICCV2021W/AROW/html/Zhang_Countering_Adversarial_Examples_Combining_Input_Transformation_and_Noisy_Training_ICCVW_2021_paper.html',
        'arxivlink':'https://arxiv.org/abs/2106.13394',
        'codelink':'',
    },
    {
        'title':'P. Gao, P. Zhang and A. Smolic, "Quality Assessment for Omnidirectional Video: A Spatio-Temporal Distortion Modeling Approach," in IEEE Transactions on Multimedia, vol. 24, pp. 1-16, 2022.',
        'year':2020,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/9296376',
        'arxivlink':'',
        'codelink':'https://github.com/I2-Multimedia-Lab/360-video-experimental-platform',
    },
    {
        'title':'P. Zhang and P. Gao, "Quality Assessment for Omnidirectional Video with Consideration of Temporal Distortion Variations," 2019 IEEE Visual Communications and Image Processing (VCIP), Sydney, NSW, Australia, 2019, pp. 1-4, doi: 10.1109/VCIP47243.2019.8966002.',
        'year':2019,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/8966002',
        'arxivlink':'',
        'codelink':'https://github.com/I2-Multimedia-Lab/360-video-experimental-platform',
    },
    {
        'title':'T. Zhu and P. Gao, "An Improved Gaussian Mixture Model Based Hole-filling Algorithm Exploiting Depth Information," 2019 IEEE Visual Communications and Image Processing (VCIP), Sydney, NSW, Australia, 2019, pp. 1-4, doi: 10.1109/VCIP47243.2019.8965964.',
        'year':2019,
        'paperlink':'https://ieeexplore.ieee.org/abstract/document/8965964',
        'arxivlink':'',
        'codelink':'',
    },
]
